### ISSUE TITLE
add instructions for SRC

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/src-jupyter-workshop-template#3]

**Comment by AristotleKandylas** [comment]
@jelletreep if you like i can include html code in the README.md file for collapsible boxes. then you can just include the useful information there. Let me know if that helps you.

**Comment by jelletreep** [comment]
@AristotleKandylas , I added the instructions. Feel free to improve the appearance using boxes, or move things around to whatever you think is best!

**Comment by AristotleKandylas** [comment]
@jelletreep could you please add on top of the repository the badge from the zenodo publication. Thanks in advance

**Comment by jelletreep** [comment]
@AristotleKandylas done! Feel free to close this issue if you consider it ready.

**Comment by AristotleKandylas** [comment]
@jelletreep i think README.md file looks good at this stage. I can close the issue and we can re-open it in the future.
